[workspace]
resolver = "3"
members = [
    "apps/desktop_pet",
    "apps/desktop_pet/frontend",
    "apps/server",
    "apps/stats_server",
    "crates/ai_core",
    "crates/chat_application",
    "crates/chat_domain",
    "crates/shared",
    "crates/persistence",
    "crates/pet_domain",
    "crates/telemetry",
    "crates/ui",
]

[workspace.package]
version = "0.2.3"
edition = "2024"

[workspace.dependencies]
any_spawner = { version = "0.3", features = ["tokio"] }
async-trait = "0.1"
axum = { version = "0.8", features = ["ws"] }

dotenv = "0.15"

leptos = "0.8"
leptos_axum = "0.8"
leptos_config = "0.8"
leptos_router = "0.8"

libc = "0.2"

opentelemetry = "0.33"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

sha2 = "0.11"

sqlx = { version = "0.9", features = ["runtime-tokio", "macros", "postgres"] }

thiserror = "2.0"
tokio = { version = "1.53", features = ["full"] }
tracing = "0.1"

uuid = { version = "1.28", features = ["serde", "v4", "js"] }

[[workspace.metadata.leptos]]
name = "rust_ai_chat"
bin-package = "server"
lib-package = "ui"

bin-features = ["ssr"]
lib-features = ["hydrate"]

site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
