[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[features]
default = []
ssr = ["ui/ssr"]

[dependencies]
any_spawner.workspace = true
axum.workspace = true

chat-application = { path = "../../crates/chat_application" }

dotenv.workspace = true

leptos.workspace = true
leptos_axum.workspace = true
leptos_config.workspace = true

persistence = { path = "../../crates/persistence" }

serde.workspace = true
serde_json.workspace = true

shared = { path = "../../crates/shared" }

sqlx.workspace = true

tokio.workspace = true

ui = { path = "../../crates/ui" }
uuid.workspace = true
