[package]
name = "desktop-pet"
version.workspace = true
edition = "2024"
build = "build.rs"

[dependencies]
ai-core = { path = "../../crates/ai_core" }

dotenv.workspace = true

pet-domain = { path = "../../crates/pet_domain" }

serde.workspace = true
sha2.workspace = true

tauri = { version = "2.12", features = [] }
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[build-dependencies]
tauri-build = { version = "2.7", features = [] }
