[package]
name = "chat-application"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true

chat-domain = { path = "../chat_domain" }

thiserror.workspace = true

uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
