name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@4
       - name: Check
         run: cargo check --workspan
       - name: Run tests
         run: cargo test --workspan
         
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

