name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libwebkit2gtk-4.1-dev

      - name: Check native dependencies
        run: |
          echo "GLib:"
          pkg-config --modversion glib-2.0

          echo "GTK:"
          pkg-config --modversion gtk+-3.0

          echo "libsoup:"
          pkg-config --modversion libsoup-3.0

          echo "JavaScriptCore:"
          pkg-config --modversion javascriptcoregtk-4.1

          echo "WebKitGTK:"
          pkg-config --modversion webkit2gtk-4.1

      - name: Cargo check
        run: cargo check --workspace --all-targets

      - name: Cargo test
        run: cargo test --workspace

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libwebkit2gtk-4.1-dev

      - name: Build
        run: cargo build --workspace --verbose